# Delete these routes and define your own shop routes here

sylius_product_design_configurator_plugin.static_welcome:
    path: /static-welcome/{name}
    defaults:
        _controller: SyliusProductDesignConfiguratorPlugin:Greeting:staticallyGreet
        name: ~

sylius_product_design_configurator_plugin.dynamic_welcome:
    path: /dynamic-welcome/{name}
    defaults:
        _controller: SyliusProductDesignConfiguratorPlugin:Greeting:dynamicallyGreet
        name: ~

sylius_product_design_configurator_plugin.product_design.show:
    path: /product_design/{id}
    methods: [GET]
    defaults:
        _controller: SyliusProductDesignConfiguratorPlugin:ProductDesign:show
        _sylius:
            template: ProductDesignConfigurator:Product:show.html.twig # Use a custom template.
            repository:
                method: findForStore # Use a custom repository method.
                arguments: [id] # Pass the product id from the url to the repository.
            arguments: ['expr:service("security.context").getToken().getUser()']
